# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeepdiffDb < Formula
  desc "Compare databases, detect schema drift, and generate safe SQL migration packs."
  homepage "https://iamvirul.github.io/deepdiff-db/"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamvirul/deepdiff-db/releases/download/v1.4.0/deepdiffdb_1.4.0_darwin_amd64.tar.gz"
      sha256 "8c89de3b0376422d8642781997755d51e72d895d085cf033f1bbc3406abbc9ef"

      define_method(:install) do
        bin.install "deepdiffdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamvirul/deepdiff-db/releases/download/v1.4.0/deepdiffdb_1.4.0_darwin_arm64.tar.gz"
      sha256 "d79f16b46851522401325be40a5ef9b980df83dc63bdeb07381fe438df2bc0d8"

      define_method(:install) do
        bin.install "deepdiffdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamvirul/deepdiff-db/releases/download/v1.4.0/deepdiffdb_1.4.0_linux_amd64.tar.gz"
      sha256 "78ad2cc8f123b384df79f0ebb88ac1e183268e3e9660311eccdf47ba90a2ed64"
      define_method(:install) do
        bin.install "deepdiffdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamvirul/deepdiff-db/releases/download/v1.4.0/deepdiffdb_1.4.0_linux_arm64.tar.gz"
      sha256 "a16e095e2c1023d590e248dc2b866b32fbbb915b645040d24d90811282977612"
      define_method(:install) do
        bin.install "deepdiffdb"
      end
    end
  end

  test do
    system "#{bin}/deepdiffdb", "--help"
  end
end
