version: '3.8'

services:
  db1:
    image: mysql:8.0
    container_name: mysql_resolution_engine_db1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_HOST: "%"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    ports:
      - "3320:3306"
    volumes:
      - ./init-scripts/01-prod-schema.sql:/docker-entrypoint-initdb.d/init.sql
      - resolution_engine_db1_data:/var/lib/mysql

  db2:
    image: mysql:8.0
    container_name: mysql_resolution_engine_db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_HOST: "%"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    ports:
      - "3319:3306"
    volumes:
      - ./init-scripts/02-dev-schema.sql:/docker-entrypoint-initdb.d/init.sql
      - resolution_engine_db2_data:/var/lib/mysql

volumes:
  resolution_engine_db1_data:
  resolution_engine_db2_data:
