package schema

import (
	"fmt"
	"strings"
)

// GenerateMigration generates a SQL migration script from a schema diff.
// It supports MySQL, PostgreSQL, and SQLite drivers and returns the complete
// migration script as a string wrapped in a transaction.
func GenerateMigration(diff DiffResult, driver string) (string, error) {
	driver = strings.ToLower(driver)

	// Validate driver
	switch driver {
	case "mysql", "postgres", "postgresql", "sqlite":
	default:
		return "", fmt.Errorf("unsupported driver: %s", driver)
	}

	var stmts []string

	// Add transaction start
	stmts = append(stmts, "BEGIN;")
	stmts = append(stmts, "")

	// Add header comment
	stmts = append(stmts, "-- Schema Migration Script")
	stmts = append(stmts, fmt.Sprintf("-- Generated by DeepDiff DB for %s", driver))
	stmts = append(stmts, "-- WARNING: Review this script carefully before applying to production")
	stmts = append(stmts, "")

	// Process removed tables (DROP TABLE)
	if len(diff.RemovedTables) > 0 {
		stmts = append(stmts, "-- DROP TABLES (present in prod but not in dev)")
		stmts = append(stmts, "-- WARNING: These operations will delete data!")
		for _, tableName := range diff.RemovedTables {
			stmts = append(stmts, fmt.Sprintf("-- DROP TABLE %s;", quoteIdentifier(tableName, driver)))
		}
		stmts = append(stmts, "")
	}

	// Process added tables (CREATE TABLE)
	// Note: We can't generate CREATE TABLE statements without the full table definition
	// This would require passing the dev schema to this function
	if len(diff.AddedTables) > 0 {
		stmts = append(stmts, "-- CREATE TABLES (present in dev but not in prod)")
		stmts = append(stmts, "-- WARNING: Manual table creation required - full schema not available")
		for _, tableName := range diff.AddedTables {
			stmts = append(stmts, fmt.Sprintf("-- CREATE TABLE %s (...);", quoteIdentifier(tableName, driver)))
		}
		stmts = append(stmts, "")
	}

	// Process column changes for existing tables
	for _, td := range diff.Tables {
		if td.OnlyInProd || td.OnlyInDev {
			// Skip tables that don't exist in both
			continue
		}

		if !td.HasDifferences {
			continue
		}

		stmts = append(stmts, fmt.Sprintf("-- Table: %s", td.Name))

		// Add columns
		for _, col := range td.AddedColumns {
			stmt, err := generateAddColumn(td.Name, col, driver)
			if err != nil {
				return "", fmt.Errorf("generate add column %s.%s: %w", td.Name, col.Name, err)
			}
			stmts = append(stmts, stmt)
		}

		// Drop columns (commented out by default for safety)
		if len(td.RemovedColumns) > 0 {
			stmts = append(stmts, "-- DROP COLUMNS (present in prod but not in dev)")
			stmts = append(stmts, "-- WARNING: These operations will delete data!")
			for _, col := range td.RemovedColumns {
				stmt, err := generateDropColumn(td.Name, col, driver)
				if err != nil {
					return "", fmt.Errorf("generate drop column %s.%s: %w", td.Name, col.Name, err)
				}
				stmts = append(stmts, "-- "+stmt)
			}
		}

		// Modify columns
		for _, colDiff := range td.ModifiedColumns {
			stmt, err := generateModifyColumn(td.Name, colDiff, driver)
			if err != nil {
				return "", fmt.Errorf("generate modify column %s.%s: %w", td.Name, colDiff.Column, err)
			}
			stmts = append(stmts, stmt)
		}

		stmts = append(stmts, "")
	}

	// Add transaction commit
	stmts = append(stmts, "COMMIT;")

	return strings.Join(stmts, "\n"), nil
}

// generateAddColumn generates an ALTER TABLE ADD COLUMN statement
func generateAddColumn(tableName string, col Column, driver string) (string, error) {
	quotedTable := quoteIdentifier(tableName, driver)
	quotedCol := quoteIdentifier(col.Name, driver)

	nullClause := "NOT NULL"
	if col.IsNullable {
		nullClause = "NULL"
	}

	switch driver {
	case "mysql":
		return fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s %s;", quotedTable, quotedCol, col.DataType, nullClause), nil
	case "postgres", "postgresql":
		return fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s %s;", quotedTable, quotedCol, col.DataType, nullClause), nil
	case "sqlite":
		// SQLite doesn't support NOT NULL in ADD COLUMN without a default value
		if col.IsNullable {
			return fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s;", quotedTable, quotedCol, col.DataType), nil
		}
		return fmt.Sprintf("-- ALTER TABLE %s ADD COLUMN %s %s NOT NULL; -- SQLite limitation: cannot add NOT NULL without default", quotedTable, quotedCol, col.DataType), nil
	default:
		return "", fmt.Errorf("unsupported driver: %s", driver)
	}
}

// generateDropColumn generates an ALTER TABLE DROP COLUMN statement
func generateDropColumn(tableName string, col Column, driver string) (string, error) {
	quotedTable := quoteIdentifier(tableName, driver)
	quotedCol := quoteIdentifier(col.Name, driver)

	switch driver {
	case "mysql":
		return fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s;", quotedTable, quotedCol), nil
	case "postgres", "postgresql":
		return fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s;", quotedTable, quotedCol), nil
	case "sqlite":
		return fmt.Sprintf("-- SQLite does not support DROP COLUMN directly. Manual migration required for table %s column %s", tableName, col.Name), nil
	default:
		return "", fmt.Errorf("unsupported driver: %s", driver)
	}
}

// generateModifyColumn generates an ALTER TABLE MODIFY/ALTER COLUMN statement
func generateModifyColumn(tableName string, colDiff ColumnDiff, driver string) (string, error) {
	quotedTable := quoteIdentifier(tableName, driver)
	quotedCol := quoteIdentifier(colDiff.Column, driver)

	switch driver {
	case "mysql":
		// MySQL uses MODIFY COLUMN
		// We need to specify the full column definition including NULL/NOT NULL
		dataType := colDiff.DevType
		if dataType == "" {
			dataType = colDiff.ProdType
		}

		// Determine nullable constraint - prefer DevNullable, fall back to ProdNullable
		var nullable *bool
		if colDiff.DevNullable != nil {
			nullable = colDiff.DevNullable
		} else if colDiff.ProdNullable != nil {
			nullable = colDiff.ProdNullable
		} else {
			return "", fmt.Errorf("cannot determine NULL/NOT NULL constraint for column %s.%s: both DevNullable and ProdNullable are nil", tableName, colDiff.Column)
		}

		// Construct NULL/NOT NULL clause
		var nullClause string
		if *nullable {
			nullClause = "NULL"
		} else {
			nullClause = "NOT NULL"
		}

		return fmt.Sprintf("ALTER TABLE %s MODIFY COLUMN %s %s %s;", quotedTable, quotedCol, dataType, nullClause), nil

	case "postgres", "postgresql":
		// PostgreSQL requires separate statements for type and nullable changes
		var stmts []string

		if colDiff.TypeMismatch {
			dataType := colDiff.DevType
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s;", quotedTable, quotedCol, dataType))
		}

		if colDiff.NullableMismatch && colDiff.DevNullable != nil {
			if *colDiff.DevNullable {
				stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL;", quotedTable, quotedCol))
			} else {
				stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL;", quotedTable, quotedCol))
			}
		}

		return strings.Join(stmts, "\n"), nil

	case "sqlite":
		return fmt.Sprintf("-- SQLite does not support MODIFY COLUMN. Manual migration required for table %s column %s", tableName, colDiff.Column), nil

	default:
		return "", fmt.Errorf("unsupported driver: %s", driver)
	}
}

// quoteIdentifier quotes a database identifier (table or column name) according to the driver's syntax.
// It handles schema-qualified names (e.g., "schema.table") and escapes embedded quote characters.
func quoteIdentifier(identifier string, driver string) string {
	var quoteChar string
	var escapeQuote func(string) string

	switch driver {
	case "mysql":
		quoteChar = "`"
		escapeQuote = func(s string) string {
			return strings.ReplaceAll(s, "`", "``")
		}
	case "postgres", "postgresql", "sqlite":
		quoteChar = "\""
		escapeQuote = func(s string) string {
			return strings.ReplaceAll(s, "\"", "\"\"")
		}
	default:
		// Unknown driver - return identifier as-is
		return identifier
	}

	// Split on '.' to handle schema-qualified names (e.g., "schema.table")
	parts := strings.Split(identifier, ".")
	quotedParts := make([]string, len(parts))

	for i, part := range parts {
		// Escape embedded quote characters by doubling them
		escaped := escapeQuote(part)
		// Wrap in quotes
		quotedParts[i] = quoteChar + escaped + quoteChar
	}

	// Rejoin with '.'
	return strings.Join(quotedParts, ".")
}
