package schema

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// MigrationOptions controls the behavior and safety settings for migration generation.
type MigrationOptions struct {
	// AllowDropColumn controls whether DROP COLUMN statements are uncommented.
	// When false (default), DROP COLUMN statements are commented out for safety.
	AllowDropColumn bool

	// AllowDropTable controls whether DROP TABLE statements are uncommented.
	// When false (default), DROP TABLE statements are commented out for safety.
	AllowDropTable bool

	// AllowDropIndex controls whether DROP INDEX statements are uncommented.
	// When false (default), DROP INDEX statements are commented out for safety.
	AllowDropIndex bool

	// AllowDropForeignKey controls whether DROP FOREIGN KEY statements are uncommented.
	// When false (default), DROP FOREIGN KEY statements are commented out for safety.
	AllowDropForeignKey bool

	// AllowModifyPrimaryKey controls whether primary key modification statements are uncommented.
	// When false (default), PRIMARY KEY modification statements are commented out for safety.
	AllowModifyPrimaryKey bool

	// ConfirmDestructive adds additional warnings for destructive operations.
	ConfirmDestructive bool
}

// GenerateMigration generates a SQL migration script from a schema diff.
// It supports MySQL, PostgreSQL, and SQLite drivers and returns the complete
// migration script as a string wrapped in a transaction.
// GenerateMigration generates a SQL migration script that reconciles the provided schema diff for the specified database driver.
//
// The returned script is a single string wrapped in a transaction (BEGIN/COMMIT) and includes sectioned statements and warnings
// for removed tables, added tables, added/removed/modified columns. If opts is nil, safe defaults are applied: AllowDropColumn=false,
// AllowDropTable=false and ConfirmDestructive=true; these options control whether DROP statements are emitted or commented out and
// whether extra destructive-confirmation warnings are included.
//
// Supported drivers are "mysql", "postgres", "postgresql", and "sqlite". An error is returned if the driver is unsupported or if
// generating any individual statement fails.
//
// The function automatically orders operations to respect foreign key dependencies:
// - CREATE TABLE operations are ordered so referenced tables are created first
// - DROP TABLE operations are ordered so tables with FKs are dropped first
// - Foreign key operations are placed after their referenced tables exist
func GenerateMigration(diff DiffResult, driver string, opts *MigrationOptions) (string, error) {
	return GenerateMigrationWithSchemas(diff, driver, opts, nil)
}

// GenerateMigrationWithSchemas generates a SQL migration script with full schema context.
// The prodSchema parameter enables proper ordering of DROP TABLE operations based on
// foreign key dependencies in the production schema.
func GenerateMigrationWithSchemas(diff DiffResult, driver string, opts *MigrationOptions, prodSchema *Schema) (string, error) {
	// Use safe defaults if opts is nil
	if opts == nil {
		opts = &MigrationOptions{
			AllowDropColumn:       false,
			AllowDropTable:        false,
			AllowDropIndex:        false,
			AllowDropForeignKey:   false,
			AllowModifyPrimaryKey: false,
			ConfirmDestructive:    true,
		}
	}
	driver = strings.ToLower(driver)

	// Validate driver
	switch driver {
	case "mysql", "postgres", "postgresql", "sqlite":
	default:
		return "", fmt.Errorf("unsupported driver: %s", driver)
	}

	var stmts []string

	// Add transaction start
	stmts = append(stmts, "BEGIN;")
	stmts = append(stmts, "")

	// Add header comment
	stmts = append(stmts, "-- Schema Migration Script")
	stmts = append(stmts, fmt.Sprintf("-- Generated by DeepDiff DB for %s", driver))
	stmts = append(stmts, "-- WARNING: Review this script carefully before applying to production")
	stmts = append(stmts, "")

	// Process removed tables (DROP TABLE)
	// Order tables so that tables with FKs pointing to other removed tables are dropped first
	if len(diff.RemovedTables) > 0 {
		stmts = append(stmts, "-- DROP TABLES (present in prod but not in dev)")
		stmts = append(stmts, "-- WARNING: These operations will delete data!")
		if opts.ConfirmDestructive {
			stmts = append(stmts, "-- IMPORTANT: Review carefully before executing!")
		}
		// Order removed tables by FK dependencies
		orderedRemovedTables := GetOrderedRemovedTables(diff.RemovedTables, prodSchema)
		for _, tableName := range orderedRemovedTables {
			dropStmt := fmt.Sprintf("DROP TABLE %s;", quoteIdentifier(tableName, driver))
			if !opts.AllowDropTable {
				dropStmt = "-- " + dropStmt
			}
			stmts = append(stmts, dropStmt)
		}
		stmts = append(stmts, "")
	}

	// Process added tables (CREATE TABLE)
	// Order tables so that referenced tables (via FK) are created first
	if len(diff.AddedTables) > 0 {
		stmts = append(stmts, "-- CREATE TABLES (present in dev but not in prod)")
		// Order added tables by FK dependencies - referenced tables first
		orderedAddedTables := GetOrderedAddedTables(diff.AddedTables)
		for _, table := range orderedAddedTables {
			createStmt := generateCreateTable(table, driver)
			stmts = append(stmts, createStmt)

			// Generate CREATE INDEX statements for the new table's indexes
			if len(table.Indexes) > 0 {
				for _, idx := range table.Indexes {
					idxStmt := generateCreateIndex(table.Name, idx, driver)
					stmts = append(stmts, idxStmt)
				}
			}

			// Generate ADD FOREIGN KEY statements for the new table's foreign keys
			if len(table.ForeignKeys) > 0 {
				for _, fk := range table.ForeignKeys {
					fkStmt := generateAddForeignKey(table.Name, fk, driver)
					stmts = append(stmts, fkStmt)
				}
			}
		}
		stmts = append(stmts, "")
	}

	// Process column changes for existing tables
	for _, td := range diff.Tables {
		if td.OnlyInProd || td.OnlyInDev {
			// Skip tables that don't exist in both
			continue
		}

		if !td.HasDifferences {
			continue
		}

		stmts = append(stmts, fmt.Sprintf("-- Table: %s", td.Name))

		// Add columns
		for _, col := range td.AddedColumns {
			stmt, err := generateAddColumn(td.Name, col, driver)
			if err != nil {
				return "", fmt.Errorf("generate add column %s.%s: %w", td.Name, col.Name, err)
			}
			stmts = append(stmts, stmt)
		}

		// Drop columns
		if len(td.RemovedColumns) > 0 {
			stmts = append(stmts, "-- DROP COLUMNS (present in prod but not in dev)")
			stmts = append(stmts, "-- WARNING: These operations will delete data!")
			if opts.ConfirmDestructive {
				stmts = append(stmts, "-- IMPORTANT: Review carefully before executing!")
			}
			for _, col := range td.RemovedColumns {
				stmt, err := generateDropColumn(td.Name, col, driver)
				if err != nil {
					return "", fmt.Errorf("generate drop column %s.%s: %w", td.Name, col.Name, err)
				}
				if !opts.AllowDropColumn {
					stmt = "-- " + stmt
				}
				stmts = append(stmts, stmt)
			}
		}

		// Modify columns
		for _, colDiff := range td.ModifiedColumns {
			stmt, err := generateModifyColumn(td.Name, colDiff, driver)
			if err != nil {
				return "", fmt.Errorf("generate modify column %s.%s: %w", td.Name, colDiff.Column, err)
			}
			stmts = append(stmts, stmt)
		}

		// Add indexes (present in dev but not in prod)
		if len(td.AddedIndexes) > 0 {
			stmts = append(stmts, "-- CREATE INDEXES (present in dev but not in prod)")
			for _, idx := range td.AddedIndexes {
				stmt := generateCreateIndex(td.Name, idx, driver)
				stmts = append(stmts, stmt)
			}
		}

		// Drop indexes (present in prod but not in dev)
		if len(td.RemovedIndexes) > 0 {
			stmts = append(stmts, "-- DROP INDEXES (present in prod but not in dev)")
			stmts = append(stmts, "-- WARNING: Dropping indexes may impact query performance")
			if opts.ConfirmDestructive {
				stmts = append(stmts, "-- IMPORTANT: Review carefully before executing!")
			}
			for _, idx := range td.RemovedIndexes {
				stmt := generateDropIndex(td.Name, idx, driver)
				if !opts.AllowDropIndex {
					stmt = "-- " + stmt
				}
				stmts = append(stmts, stmt)
			}
		}

		// Modified indexes (differ in columns or uniqueness)
		if len(td.ModifiedIndexes) > 0 {
			stmts = append(stmts, "-- MODIFIED INDEXES (differ between prod and dev)")
			stmts = append(stmts, "-- NOTE: To modify an index, drop and recreate it. Manual review required.")
			for _, idxDiff := range td.ModifiedIndexes {
				stmts = append(stmts, fmt.Sprintf("-- Index %s differs between prod and dev", idxDiff.Name))
				if idxDiff.ColumnsDiffer {
					stmts = append(stmts, fmt.Sprintf("--   Columns: prod=%v dev=%v", idxDiff.ProdColumns, idxDiff.DevColumns))
				}
				if idxDiff.UniqueDiffers {
					stmts = append(stmts, fmt.Sprintf("--   Unique: prod=%v dev=%v", *idxDiff.ProdUnique, *idxDiff.DevUnique))
				}
			}
		}

		// Drop foreign keys (present in prod but not in dev) - must be dropped before columns
		if len(td.RemovedForeignKeys) > 0 {
			stmts = append(stmts, "-- DROP FOREIGN KEYS (present in prod but not in dev)")
			stmts = append(stmts, "-- WARNING: Dropping foreign keys removes referential integrity constraints")
			if opts.ConfirmDestructive {
				stmts = append(stmts, "-- IMPORTANT: Review carefully before executing!")
			}
			for _, fk := range td.RemovedForeignKeys {
				stmt := generateDropForeignKey(td.Name, fk, driver)
				if !opts.AllowDropForeignKey {
					stmt = "-- " + stmt
				}
				stmts = append(stmts, stmt)
			}
		}

		// Add foreign keys (present in dev but not in prod)
		if len(td.AddedForeignKeys) > 0 {
			stmts = append(stmts, "-- ADD FOREIGN KEYS (present in dev but not in prod)")
			for _, fk := range td.AddedForeignKeys {
				stmt := generateAddForeignKey(td.Name, fk, driver)
				stmts = append(stmts, stmt)
			}
		}

		// Modified foreign keys (differ between prod and dev)
		if len(td.ModifiedForeignKeys) > 0 {
			stmts = append(stmts, "-- MODIFIED FOREIGN KEYS (differ between prod and dev)")
			stmts = append(stmts, "-- NOTE: To modify a foreign key, drop and recreate it. Manual review required.")
			for _, fkDiff := range td.ModifiedForeignKeys {
				stmts = append(stmts, fmt.Sprintf("-- Foreign key %s differs between prod and dev", fkDiff.Name))
				if fkDiff.ColumnsDiffer {
					stmts = append(stmts, fmt.Sprintf("--   Columns: prod=%v dev=%v", fkDiff.ProdColumns, fkDiff.DevColumns))
				}
				if fkDiff.ReferencedTableDiffers {
					stmts = append(stmts, fmt.Sprintf("--   Referenced table: prod=%s dev=%s", fkDiff.ProdReferencedTable, fkDiff.DevReferencedTable))
				}
				if fkDiff.ReferencedColumnsDiffer {
					stmts = append(stmts, fmt.Sprintf("--   Referenced columns: prod=%v dev=%v", fkDiff.ProdReferencedColumns, fkDiff.DevReferencedColumns))
				}
				if fkDiff.OnDeleteDiffers {
					stmts = append(stmts, fmt.Sprintf("--   ON DELETE: prod=%s dev=%s", fkDiff.ProdOnDelete, fkDiff.DevOnDelete))
				}
				if fkDiff.OnUpdateDiffers {
					stmts = append(stmts, fmt.Sprintf("--   ON UPDATE: prod=%s dev=%s", fkDiff.ProdOnUpdate, fkDiff.DevOnUpdate))
				}
			}
		}

		// Primary key modifications
		if td.PrimaryKeyDiff != nil {
			stmts = append(stmts, "-- PRIMARY KEY MODIFICATION")
			stmts = append(stmts, "-- WARNING: Modifying primary keys is a complex operation that may require data migration")
			if opts.ConfirmDestructive {
				stmts = append(stmts, "-- IMPORTANT: Review carefully and test in non-production environment first!")
			}
			pkStmts := generateModifyPrimaryKey(td.Name, td.PrimaryKeyDiff, driver, opts.AllowModifyPrimaryKey)
			stmts = append(stmts, pkStmts...)
		}

		stmts = append(stmts, "")
	}

	// Add transaction commit
	stmts = append(stmts, "COMMIT;")

	return strings.Join(stmts, "\n"), nil
}

// generateAddColumn generates an ALTER TABLE ADD COLUMN statement
func generateAddColumn(tableName string, col Column, driver string) (string, error) {
	quotedTable := quoteIdentifier(tableName, driver)
	quotedCol := quoteIdentifier(col.Name, driver)

	nullClause := "NOT NULL"
	if col.IsNullable {
		nullClause = "NULL"
	}

	// Build default clause if present
	var defaultClause string
	if col.DefaultValue != nil {
		defaultClause = fmt.Sprintf(" DEFAULT %s", *col.DefaultValue)
	}

	switch driver {
	case "mysql":
		return fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s %s%s;", quotedTable, quotedCol, col.DataType, nullClause, defaultClause), nil
	case "postgres", "postgresql":
		return fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s %s%s;", quotedTable, quotedCol, col.DataType, nullClause, defaultClause), nil
	case "sqlite":
		// SQLite doesn't support NOT NULL in ADD COLUMN without a default value
		if col.IsNullable {
			return fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s%s;", quotedTable, quotedCol, col.DataType, defaultClause), nil
		}
		if col.DefaultValue != nil {
			return fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s NOT NULL%s;", quotedTable, quotedCol, col.DataType, defaultClause), nil
		}
		return fmt.Sprintf("-- ALTER TABLE %s ADD COLUMN %s %s NOT NULL; -- SQLite limitation: cannot add NOT NULL without default", quotedTable, quotedCol, col.DataType), nil
	default:
		return "", fmt.Errorf("unsupported driver: %s", driver)
	}
}

// generateDropColumn generates an ALTER TABLE DROP COLUMN statement
func generateDropColumn(tableName string, col Column, driver string) (string, error) {
	quotedTable := quoteIdentifier(tableName, driver)
	quotedCol := quoteIdentifier(col.Name, driver)

	switch driver {
	case "mysql":
		return fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s;", quotedTable, quotedCol), nil
	case "postgres", "postgresql":
		return fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s;", quotedTable, quotedCol), nil
	case "sqlite":
		return fmt.Sprintf("-- SQLite does not support DROP COLUMN directly. Manual migration required for table %s column %s", tableName, col.Name), nil
	default:
		return "", fmt.Errorf("unsupported driver: %s", driver)
	}
}

// generateModifyColumn generates an ALTER TABLE MODIFY/ALTER COLUMN statement
func generateModifyColumn(tableName string, colDiff ColumnDiff, driver string) (string, error) {
	quotedTable := quoteIdentifier(tableName, driver)
	quotedCol := quoteIdentifier(colDiff.Column, driver)

	switch driver {
	case "mysql":
		// MySQL uses MODIFY COLUMN
		// We need to specify the full column definition including NULL/NOT NULL and DEFAULT
		dataType := colDiff.DevType
		if dataType == "" {
			dataType = colDiff.ProdType
		}

		// Determine nullable constraint - prefer DevNullable, fall back to ProdNullable
		var nullable *bool
		if colDiff.DevNullable != nil {
			nullable = colDiff.DevNullable
		} else if colDiff.ProdNullable != nil {
			nullable = colDiff.ProdNullable
		} else {
			return "", fmt.Errorf("cannot determine NULL/NOT NULL constraint for column %s.%s: both DevNullable and ProdNullable are nil", tableName, colDiff.Column)
		}

		// Construct NULL/NOT NULL clause
		var nullClause string
		if *nullable {
			nullClause = "NULL"
		} else {
			nullClause = "NOT NULL"
		}

		// Determine default value
		var defaultClause string
		if colDiff.DefaultMismatch {
			// If there's a default mismatch, use DevDefault (could be nil, meaning remove default)
			if colDiff.DevDefault != nil {
				defaultClause = fmt.Sprintf(" DEFAULT %s", *colDiff.DevDefault)
			}
		} else {
			// No default mismatch - use whichever is available
			if colDiff.DevDefault != nil {
				defaultClause = fmt.Sprintf(" DEFAULT %s", *colDiff.DevDefault)
			} else if colDiff.ProdDefault != nil {
				defaultClause = fmt.Sprintf(" DEFAULT %s", *colDiff.ProdDefault)
			}
		}

		return fmt.Sprintf("ALTER TABLE %s MODIFY COLUMN %s %s %s%s;", quotedTable, quotedCol, dataType, nullClause, defaultClause), nil

	case "postgres", "postgresql":
		// PostgreSQL requires separate statements for type, nullable, and default changes
		var stmts []string

		if colDiff.TypeMismatch {
			dataType := colDiff.DevType
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s;", quotedTable, quotedCol, dataType))
		}

		if colDiff.NullableMismatch && colDiff.DevNullable != nil {
			if *colDiff.DevNullable {
				stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL;", quotedTable, quotedCol))
			} else {
				stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL;", quotedTable, quotedCol))
			}
		}

		if colDiff.DefaultMismatch {
			if colDiff.DevDefault != nil {
				stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s;", quotedTable, quotedCol, *colDiff.DevDefault))
			} else {
				stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT;", quotedTable, quotedCol))
			}
		}

		return strings.Join(stmts, "\n"), nil

	case "sqlite":
		return fmt.Sprintf("-- SQLite does not support MODIFY COLUMN. Manual migration required for table %s column %s", tableName, colDiff.Column), nil

	default:
		return "", fmt.Errorf("unsupported driver: %s", driver)
	}
}

// quoteIdentifier quotes a database identifier (table or column name) according to the driver's syntax.
// It handles schema-qualified names (e.g., "schema.table") and escapes embedded quote characters.
func quoteIdentifier(identifier string, driver string) string {
	var quoteChar string
	var escapeQuote func(string) string

	switch driver {
	case "mysql":
		quoteChar = "`"
		escapeQuote = func(s string) string {
			return strings.ReplaceAll(s, "`", "``")
		}
	case "postgres", "postgresql", "sqlite":
		quoteChar = "\""
		escapeQuote = func(s string) string {
			return strings.ReplaceAll(s, "\"", "\"\"")
		}
	default:
		// Unknown driver - return identifier as-is
		return identifier
	}

	// Split on '.' to handle schema-qualified names (e.g., "schema.table")
	parts := strings.Split(identifier, ".")
	quotedParts := make([]string, len(parts))

	for i, part := range parts {
		// Escape embedded quote characters by doubling them
		escaped := escapeQuote(part)
		// Wrap in quotes
		quotedParts[i] = quoteChar + escaped + quoteChar
	}

	// Rejoin with '.'
	return strings.Join(quotedParts, ".")
}

// generateCreateIndex generates a CREATE INDEX or CREATE UNIQUE INDEX statement.
func generateCreateIndex(tableName string, idx Index, driver string) string {
	quotedTable := quoteIdentifier(tableName, driver)
	quotedIndex := quoteIdentifier(idx.Name, driver)

	// Quote column names
	quotedCols := make([]string, len(idx.Columns))
	for i, col := range idx.Columns {
		quotedCols[i] = quoteIdentifier(col, driver)
	}
	colList := strings.Join(quotedCols, ", ")

	if idx.IsUnique {
		return fmt.Sprintf("CREATE UNIQUE INDEX %s ON %s (%s);", quotedIndex, quotedTable, colList)
	}
	return fmt.Sprintf("CREATE INDEX %s ON %s (%s);", quotedIndex, quotedTable, colList)
}

// generateDropIndex generates a DROP INDEX statement.
// MySQL requires the table name in DROP INDEX, while PostgreSQL and SQLite do not.
func generateDropIndex(tableName string, idx Index, driver string) string {
	quotedIndex := quoteIdentifier(idx.Name, driver)

	switch driver {
	case "mysql":
		quotedTable := quoteIdentifier(tableName, driver)
		return fmt.Sprintf("DROP INDEX %s ON %s;", quotedIndex, quotedTable)
	case "postgres", "postgresql", "sqlite":
		return fmt.Sprintf("DROP INDEX %s;", quotedIndex)
	default:
		return fmt.Sprintf("-- DROP INDEX %s; -- unsupported driver", idx.Name)
	}
}

// generateCreateTable generates a CREATE TABLE statement with all columns, primary key, and indexes.
func generateCreateTable(table Table, driver string) string {
	var b strings.Builder
	quotedTable := quoteIdentifier(table.Name, driver)

	b.WriteString(fmt.Sprintf("CREATE TABLE %s (\n", quotedTable))

	// Collect column definitions
	var colDefs []string

	// Sort columns for deterministic output
	colNames := make([]string, 0, len(table.Columns))
	for name := range table.Columns {
		colNames = append(colNames, name)
	}
	sort.Strings(colNames)

	for _, colName := range colNames {
		col := table.Columns[colName]
		colDef := generateColumnDefinition(col, driver)
		colDefs = append(colDefs, "  "+colDef)
	}

	// Add primary key constraint if present
	if len(table.PrimaryKey) > 0 {
		pkCols := make([]string, len(table.PrimaryKey))
		for i, col := range table.PrimaryKey {
			pkCols[i] = quoteIdentifier(col, driver)
		}
		pkDef := fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(pkCols, ", "))
		colDefs = append(colDefs, pkDef)
	}

	b.WriteString(strings.Join(colDefs, ",\n"))
	b.WriteString("\n)")

	// Add MySQL-specific table options
	if driver == "mysql" {
		b.WriteString(" ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")
	}

	b.WriteString(";")

	return b.String()
}

// generateColumnDefinition generates a column definition for CREATE TABLE.
func generateColumnDefinition(col Column, driver string) string {
	var parts []string

	quotedName := quoteIdentifier(col.Name, driver)
	parts = append(parts, quotedName)
	parts = append(parts, col.DataType)

	if !col.IsNullable {
		parts = append(parts, "NOT NULL")
	}

	if col.DefaultValue != nil {
		defaultVal := *col.DefaultValue
		// Check if default value needs quoting (non-numeric, non-function values)
		if needsQuoting(defaultVal) {
			parts = append(parts, fmt.Sprintf("DEFAULT '%s'", defaultVal))
		} else {
			parts = append(parts, fmt.Sprintf("DEFAULT %s", defaultVal))
		}
	}

	return strings.Join(parts, " ")
}

// needsQuoting determines if a default value needs to be quoted.
func needsQuoting(val string) bool {
	// Don't quote NULL
	if strings.ToUpper(val) == "NULL" {
		return false
	}
	// Don't quote boolean values
	if strings.ToUpper(val) == "TRUE" || strings.ToUpper(val) == "FALSE" {
		return false
	}
	// Don't quote numeric values
	if _, err := strconv.ParseFloat(val, 64); err == nil {
		return false
	}
	// Don't quote function calls (contain parentheses)
	if strings.Contains(val, "(") && strings.Contains(val, ")") {
		return false
	}
	// Don't quote CURRENT_TIMESTAMP and similar
	if strings.HasPrefix(strings.ToUpper(val), "CURRENT_") {
		return false
	}
	return true
}

// generateAddForeignKey generates an ALTER TABLE ADD CONSTRAINT FOREIGN KEY statement.
func generateAddForeignKey(tableName string, fk ForeignKey, driver string) string {
	quotedTable := quoteIdentifier(tableName, driver)
	quotedFK := quoteIdentifier(fk.Name, driver)
	quotedRefTable := quoteIdentifier(fk.ReferencedTable, driver)

	// Quote column names
	quotedCols := make([]string, len(fk.Columns))
	for i, col := range fk.Columns {
		quotedCols[i] = quoteIdentifier(col, driver)
	}
	colList := strings.Join(quotedCols, ", ")

	// Quote referenced column names
	quotedRefCols := make([]string, len(fk.ReferencedColumns))
	for i, col := range fk.ReferencedColumns {
		quotedRefCols[i] = quoteIdentifier(col, driver)
	}
	refColList := strings.Join(quotedRefCols, ", ")

	// Build ON DELETE and ON UPDATE clauses
	var actions []string
	if fk.OnDelete != "" && strings.ToUpper(fk.OnDelete) != "NO ACTION" {
		actions = append(actions, fmt.Sprintf("ON DELETE %s", strings.ToUpper(fk.OnDelete)))
	}
	if fk.OnUpdate != "" && strings.ToUpper(fk.OnUpdate) != "NO ACTION" {
		actions = append(actions, fmt.Sprintf("ON UPDATE %s", strings.ToUpper(fk.OnUpdate)))
	}

	actionClause := ""
	if len(actions) > 0 {
		actionClause = " " + strings.Join(actions, " ")
	}

	switch driver {
	case "sqlite":
		// SQLite doesn't support ADD CONSTRAINT for foreign keys after table creation
		return fmt.Sprintf("-- SQLite limitation: Cannot add foreign key %s after table creation. Table recreation required.", fk.Name)
	default:
		return fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)%s;",
			quotedTable, quotedFK, colList, quotedRefTable, refColList, actionClause)
	}
}

// generateDropForeignKey generates an ALTER TABLE DROP FOREIGN KEY/CONSTRAINT statement.
func generateDropForeignKey(tableName string, fk ForeignKey, driver string) string {
	quotedTable := quoteIdentifier(tableName, driver)
	quotedFK := quoteIdentifier(fk.Name, driver)

	switch driver {
	case "mysql":
		return fmt.Sprintf("ALTER TABLE %s DROP FOREIGN KEY %s;", quotedTable, quotedFK)
	case "postgres", "postgresql":
		return fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT %s;", quotedTable, quotedFK)
	case "sqlite":
		return fmt.Sprintf("-- SQLite limitation: Cannot drop foreign key %s. Table recreation required.", fk.Name)
	default:
		return fmt.Sprintf("-- DROP FOREIGN KEY %s; -- unsupported driver", fk.Name)
	}
}

// generateModifyPrimaryKey generates statements to modify primary key.
// Returns a slice of SQL statements as primary key modification may require multiple steps.
func generateModifyPrimaryKey(tableName string, pkDiff *PrimaryKeyDiff, driver string, allowModify bool) []string {
	var stmts []string
	quotedTable := quoteIdentifier(tableName, driver)

	// Quote new primary key columns
	quotedNewCols := make([]string, len(pkDiff.DevColumns))
	for i, col := range pkDiff.DevColumns {
		quotedNewCols[i] = quoteIdentifier(col, driver)
	}
	newColList := strings.Join(quotedNewCols, ", ")

	switch driver {
	case "mysql":
		// MySQL: DROP PRIMARY KEY, then ADD PRIMARY KEY
		dropStmt := fmt.Sprintf("ALTER TABLE %s DROP PRIMARY KEY;", quotedTable)
		addStmt := fmt.Sprintf("ALTER TABLE %s ADD PRIMARY KEY (%s);", quotedTable, newColList)

		if !allowModify {
			dropStmt = "-- " + dropStmt
			addStmt = "-- " + addStmt
		}

		if len(pkDiff.ProdColumns) > 0 {
			stmts = append(stmts, fmt.Sprintf("-- Current primary key: (%s)", strings.Join(pkDiff.ProdColumns, ", ")))
			stmts = append(stmts, fmt.Sprintf("-- New primary key: (%s)", strings.Join(pkDiff.DevColumns, ", ")))
			stmts = append(stmts, dropStmt)
		}
		if len(pkDiff.DevColumns) > 0 {
			stmts = append(stmts, addStmt)
		}

	case "postgres", "postgresql":
		// PostgreSQL: DROP CONSTRAINT pk_name, then ADD PRIMARY KEY
		// Note: We don't know the constraint name, so we use a placeholder
		dropStmt := fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT %s_pkey;", quotedTable, tableName)
		addStmt := fmt.Sprintf("ALTER TABLE %s ADD PRIMARY KEY (%s);", quotedTable, newColList)

		if !allowModify {
			dropStmt = "-- " + dropStmt
			addStmt = "-- " + addStmt
		}

		if len(pkDiff.ProdColumns) > 0 {
			stmts = append(stmts, fmt.Sprintf("-- Current primary key: (%s)", strings.Join(pkDiff.ProdColumns, ", ")))
			stmts = append(stmts, fmt.Sprintf("-- New primary key: (%s)", strings.Join(pkDiff.DevColumns, ", ")))
			stmts = append(stmts, "-- NOTE: Replace 'tablename_pkey' with actual constraint name if different")
			stmts = append(stmts, dropStmt)
		}
		if len(pkDiff.DevColumns) > 0 {
			stmts = append(stmts, addStmt)
		}

	case "sqlite":
		// SQLite doesn't support modifying primary keys directly
		stmts = append(stmts, fmt.Sprintf("-- SQLite limitation: Cannot modify primary key for table %s", tableName))
		stmts = append(stmts, fmt.Sprintf("-- Current primary key: (%s)", strings.Join(pkDiff.ProdColumns, ", ")))
		stmts = append(stmts, fmt.Sprintf("-- New primary key: (%s)", strings.Join(pkDiff.DevColumns, ", ")))
		stmts = append(stmts, "-- Manual table recreation required:")
		stmts = append(stmts, "-- 1. Create new table with correct primary key")
		stmts = append(stmts, fmt.Sprintf("-- 2. Copy data from %s to new table", tableName))
		stmts = append(stmts, fmt.Sprintf("-- 3. Drop old table %s", tableName))
		stmts = append(stmts, fmt.Sprintf("-- 4. Rename new table to %s", tableName))
	}

	return stmts
}
